name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@953c51da7e4c2c681f15c70513cb803c8fa461cc # v0.44.3
