name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
