name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@6373540d4ab86c4ce044b6a67e96aecddf22c7c9 # v0.45.1
